### ISSUE TITLE
Applying 5S to your project organization

### ISSUE THREAD

**Issue by johnblust** [fishtown-analytics/docs.getdbt.com#1258]
### Contact Details

@patkearns10

### This issue is being created to promote an approved Discussion.

- [X] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

This article predates the Discussion system, and has been outlined and drafted already. It's starting directly as an issue.

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

This article predates the Discussion system, and has been outlined and drafted already. It's starting directly as an issue. [Original Issue Link](https://github.com/dbt-labs/dbt-technical-blog-writing/issues/68#event-5806117853)

### Link to the initial outline we will develop through this Issue.

https://docs.google.com/document/d/143h-CUGXUvpxUV7j9oLAWRb1LPZYHEtHexRfQztWqlg/edit?usp=sharing

**Comment by KiraFuruichi** [comment]
Hey @patkearns10 @johnblust should I close out this issue? Or was this closed with https://github.com/dbt-labs/docs.getdbt.com/issues/1270?

**Comment by patkearns10** [comment]
Hi @KiraFuruichi - this is a separate writeup! I haven't come to a meeting in a long time though, so not sure what the process is like anymore. If this sounds like something we would like to post in the future, please let me know and I would be happy to work on it!
Also, I had this one in the backlog too: https://github.com/dbt-labs/docs.getdbt.com/discussions/1306 about Audit Helper.

**Comment by KiraFuruichi** [comment]
ok thanks @patkearns10 ! let me take a close look at these two issues and I'll get back to you next week :)

**Comment by KiraFuruichi** [comment]
Ok @patkearns10 I was reading through your outline and kept thinking to myself, "Why does this seem so familiar?" and then it dawned on me...5S is at the root of Marie Kondo's cleaning methods...aka the article Lauren wrote on [Kon Mari'ing your migrations](https://docs.getdbt.com/blog/marie-kondo-query-migration). There's definitely some differentiations between your outline and Lauren's post (ex. hers is about migration, yours is about overall project health; you explicitly call out the 5S method, whereas hers is more of a subtle nod to it), but definitely very common themes in both your outline and her post.

Because the overall sentiment is pretty similar in both, I'm wondering how your outline can possibly be used as a Part 2 (ex "Maintaining a dbt project with 5S/KonMari") or a deep-dive into one of the elements Lauren touches on in her article. 

Let me know if you disagree with this assessment. I'm happy to think through how we can utilize this content (since it's rich and meaningful in different ways than Lauren's post). My other line of thinking is that this 5S mindset would make a great TikTok video on our account hahah

**Comment by patkearns10** [comment]
I do see some common themes there! 

I am fine with this being a Part 2 of her post, and modifying it flow that way. I don't want to deep dive into one of her elements though, because I feel like that would be a whole new article to write.

Totally fine with me for you to pick some parts and have someone else do a TikTok video if you please!

**Comment by patkearns10** [comment]
@KiraFuruichi  -- I am wondering if you would like to give this a second look! I teamed up with Lauren Benezra to review/edit/condense some of the material so that it is easier to digest and flows more with the previous article. 
https://docs.google.com/document/d/143h-CUGXUvpxUV7j9oLAWRb1LPZYHEtHexRfQztWqlg/edit#

**Comment by KiraFuruichi** [comment]
will take a look this week, thanks for sharing, Pat!

**Comment by KiraFuruichi** [comment]
@patkearns10 took a look today—overall, I really like the approach you took around building a dbt project for scale from an _organizational_ perspective. I think it's a nice contrast to Dave's How to Build a Mature dbt Project, since that's focused more on the technical. 

I left some pretty specific comments and suggestions in your doc, so please lmk how you feel about them. I think my two biggest thematic suggestions for the piece are:
- Pairing down some of the writing to be less repetitive or wordy; we can together on pairing some of the less technical writing, so not stressed about this at all!
- Really tie/lean in the concept of "small, continual improvements" throughout your post; I _really_ liked this framing and it makes 5S seems so much more approachable to the standard data team.

Lmk how you feel about this feedback—thanks again for sharing your writing!

**Comment by runleonarun** [comment]
@patkearns10 and @KiraFuruichi Are we moving forward with this, or should I close this issue out?

**Comment by patkearns10** [comment]
Hi @runleonarun ! Thank you for following up. This got thrown on the backburner for me, but I think I can wrap it up quickly. I'll look into it this week, if you still want it for the site. If not, definitely let me know!

**Comment by runleonarun** [comment]
Hi @patkearns10! No rush from me! I was just triaging issues and making sure they aren't stale. @KiraFuruichi can let us know if this is still a 👍🏻

**Comment by KiraFuruichi** [comment]
Hey yeah would still love to feature this on the site, @patkearns10 ! lmk when you want another review :)

**Comment by jasnonaz** [comment]
Gonna close this out for now
