### ISSUE TITLE
New global config: `cache_selected_only`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1273]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

- https://docs.getdbt.com/reference/global-configs

### What part(s) of the page would you like to see updated?

- Add new "global" config, `cache_selected_only`, based on the addition in https://github.com/dbt-labs/dbt-core/pull/4860
- Call out that this is "experimental" functionality, which may significantly reduce runtime overhead in large warehouses but may also have some unanticipated / unaccounted-for rough edges. We could use a callout similar to the one we use on https://docs.getdbt.com/docs/building-a-dbt-project/metrics

### Additional information

The PR is not yet merged, but likely to be included in v1.1.0rc1

**Comment by runleonarun** [comment]
Leona note: removed from PR. Need new PR
## Cache for selected models only

Supply the `--cache_selected_only` flag to `dbt run` to make dbt Cache schema for selected models only instead of caching all schemas in a project. You can set `selected_schema_cache: true` in `profile.yml` as general config for a project but can override that with --cache_selected_only for specific scenario.

For example, you can

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/docs.getdbt.com/pull/1327
