### ISSUE TITLE
Update Airflow spiritual alignment blog article 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2325]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

The subsection https://docs.getdbt.com/blog/dbt-airflow-spiritual-alignment#setting-up-airflow-and-dbt-cloud 

### What part(s) of the page would you like to see updated?

Review step 3 in subsection and see how it should be updated. 

Some background:
Step 3 referenced a broken link and there wasn't a clear replacement link for it. To fix the broken link and preserve the flow, the step no longer contains the link and is struck through. See PR #2315 for more details.

**Comment by johnblust** [comment]
@jasnonaz This step-by-step section isn't useful without being able to see the example that no longer exists. I instructed Matt and Ly to just strikethrough the text so they aren't blocked, but definitely not a long-term solution.

One option that jumps out to me is reworking this article entirely because I remember in hindsight, it didn't feel like the best fit for DevBlog. Secondly, I've heard murmurs from ProServ that this content should probably get updated now that Python functionality is here.

The second option would be to work with Sung to rework that section and leave the rest of the content as-is, but not sure how high of a priority that would be compared to the first option.

Both options are heavier lift solutions so I'm curious what your thoughts are. One thing to keep in mind, is this page does get a decent amount of monthly search traffic for "dbt airflow," so ideally, we would want this page to be accurate.

**Comment by jasnonaz** [comment]
We don't have capacity to do a heavy rewrite atm - I think the option would be to depcrecate unless someone feels like they have capacity to help with this. Another would be to point to the [airflow guide](https://docs.getdbt.com/blog/dbt-airflow-spiritual-alignment#setting-up-airflow-and-dbt-cloud) as long as we still feel good about the content there.

I'm curious what @sungchun12 thinks as the original author of the blog.

**Comment by sungchun12** [comment]
@johnblust @jasnonaz I'm happy to own a rewrite of the relevant sections. I still send this blog all the time because the first half articulates why dbt + airflow well with customers all the time. Feel free to slack me for tactical next steps!

**Comment by jasnonaz** [comment]
Awesome thank @sungchun12!! Imo this is a great fit for the dev blog and we should absolutely get it updated and keep it. @sungchun12 do you feel comfortable looking into the issue Ly pointed out and rewriting to address (while also making sure the posts fits in with how the product is evolving).

One meta-point is that, in general the idea is that dev blogs are point in time snapshots that do not need to be permanelty kept up to date, although we should add a note at the top if things have changed. Guides are where we are preserving knowledge that should always be correct and up to date with our best practices. If we think this is a high leverage enough piece that we'll want to commit to supporting it indefinitely (which seems reasonable given Sung's comment) we might want to consider moving this over to Guides.

**Comment by sungchun12** [comment]
@jasnonaz Happy to own this starting Monday next week! I'll post an update here, and potentially link a rewrite here in the same breath.

**Comment by sungchun12** [comment]
@jasnonaz @johnblust added you both for review to the above PR. I updated the links and removed language relating to using a custom python call for dbt Cloud in airflow. 

Instead of rewriting the setting up airflow with dbt Cloud section, I point the audience to the fully fleshed out guide.
