### ISSUE TITLE
How we slimmed down Slim CI/CD to use 10000X fewer data on pull requests

### ISSUE THREAD

**Issue by gabriel-inventa** [fishtown-analytics/docs.getdbt.com#2511]
### Contact Details

gabriel@inventa.shop

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

In this article, we’re going to cover how to configure a dbt Slim CI/CD pipeline to make it more efficient, improving run times without losing the ability to test recent changes against the production DAG. The article is focused on dbt cloud, but it can be extended to any user of dbt core. Its target are analytics engineer and data engineers interested in improving developer experience and reduce costs with a more efficient setup of dbt's Slim CI/CD capabilities.

### Link to an initial outline.

https://medium.com/building-inventa/how-we-slimmed-down-slim-ci-for-dbt-cloud-6a944e7574e2

**Comment by KiraFuruichi** [comment]
Hey @gabriel-inventa, I'm Kira, a technical writer here at dbt Labs and a member of our Developer Hub Team who helps manage the dbt Developer Blog. @jasnonaz, a member from dbt Labs, will be the dedicated resource for you for this piece!

The team is excited for this piece and the existing blog is very interesting; cannot wait to get even more practitioner eyes on this.

The general turnaround time for Developer Blog posts is 6 weeks (from GitHub Issue submission to publication), but we work with you all on the timeline that's best for you (especially with the holidays around the corner). Since this blog is more formed than most submissions, next step is Jason will review and make any suggestions (editorial or technical) and then pass it back to you within a week or so. This back and forth will go on as long as y'all need to get it in final shape and your communication will happen here in the issue.

Once you have a final draft, Jason will create a PR in our docs repo and ensure the new Developer Blog post is shared across the dbt Labs social media accounts :) 

Lmk how that sounds to you all or if you have any questions!

**Comment by runleonarun** [comment]
Hi @gabriel-inventa! While this topic and article sound compelling, we are not prioritizing this category of content at this time. In the future, if we have a call for this topic, we will invite your submission!
