### ISSUE TITLE
Make grouping a first-class citizen in your data quality checks

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#2566]
### Contact Details

I'm @joellabes, @Emily Riederer is the author!

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This is primarily a cross-post of Emily's piece from last year which led to the introduction of `group_by_columns` to a lot of dbt utils' tests this year: https://www.emilyriederer.com/post/grouping-data-quality

Potentially with some updates based on some other talks she has given, and obviously since the original piece went live the changes she advocated for have actually been made, so that part will need tweaked. 

### Link to an initial outline.

https://www.emilyriederer.com/post/grouping-data-quality

**Comment by emilyriederer** [comment]
Commenting to follow the conversation (looks like the wrong Emily got tagged!) Look forward to working together to get this published!

**Comment by KiraFuruichi** [comment]
Hey @joellabes and @emilyriederer, thanks for opening up this issue! 

Since this is a pretty-formed blog piece (and Joel was involved in the utils work around this), Joel will act as the primary resource to help get this live from dbt Labs' end. Joel, @johnblust can provide PR or promotion support if needed :) 

For context, the general turnaround time for Developer Blog posts is 6 weeks (from GitHub Issue submission to publication), but we work with you all on the timeline that's best for you (especially with the holidays around the corner). Since this blog is more formed than most submissions, next step is Joel will review and make any suggestions (editorial or technical) and then pass it back to you. This back and forth will go on as long as y'all need to get it in final shape and your communication will happen here in the issue.

Once you have a final draft, Joel or John will create a PR in our docs repo and ensure the new Developer Blog post is shared across the dbt Labs social media accounts :)

Lmk how that sounds to you all or if y'all have any questions!

**Comment by joellabes** [comment]
@emilyriederer I've made a google doc with your original post's text here: https://docs.google.com/document/d/18v52FkfDBs8GVI7PoDlhe9RGJGPCCBcq2gvnDs4rut0/edit# 

I propose reshaping the focus to be mindset change for practitioners as opposed to the tool maintainers themselves - more context in the doc but lmk what you think! 

Excited to get this up and running 🎉 ✨

**Comment by emilyriederer** [comment]
Thanks for the comments to get me started @joellabes ! I just finished a first pass at the updates. Let me know what you think!

**Comment by joellabes** [comment]
This is great! Did not expect you to have made such in-depth changes but I really like how it's looking now. 

It feels like it ends very suddenly - I think there could be a place for a segment on "when should you _not_ do this", which distills some of the points from your original post (especially that [not everything is equally likely to need it](https://www.emilyriederer.com/post/grouping-data-quality/#:~:text=Not%20all%20grains%20of%20data%20are%20equally%20likely%20to%20break) and that it's [more important upstream than downstream](https://www.emilyriederer.com/post/grouping-data-quality/#:~:text=High%2Drisk%20grouped%20data%20is%20possibly%20ungrouped%20further%20upstream)) between the end of the case study and the explanation about availability in dbt utils

**Comment by emilyriederer** [comment]
I cheated some! I've iterated on the idea since for talks so ended up making it more like those. (One downside of blogging is it refines your ideas enough that, by definition, the published version is the worst iteration 😆 )

Excellent point on the sudden end! I'll circle back to that later this week/weekend

**Comment by emilyriederer** [comment]
@joellabes Would you recommend that section goes before or after that "now in dbt-utils". I'm torn which is the most important last point to leave people with

**Comment by joellabes** [comment]
> One downside of blogging is it refines your ideas enough that, by definition, the published version is the worst iteration

:lolsob:

I had been thinking of the "now in dbt utils" part as an appendix/footnote - basically "here's what this is, here's why you should do it, here's when you shouldn't, oh and PS it's really easy", but whichever way you prefer!

**Comment by emilyriederer** [comment]
Just added that section! I think it's useful content, but I'm not sure if it makes a "softer langing" or not for the piece as a whole... 🤔 Welcome any thoughts on that!

**Comment by joellabes** [comment]
Nice! Just left a comment - I'm off until 8th Jan now but will check back in at the start of next year! Hope you get a lovely break too ☃️
