### ISSUE TITLE
Here is how to use Python models to add machine learning to your dbt project!

### ISSUE THREAD

**Issue by niels-tropos** [fishtown-analytics/docs.getdbt.com#2602]
### Contact Details

niels@tropos.io 

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This blog post will shortly explore dbt's new Python functionality, focussing specifically on the use of Python for Machine Learning purposes within the dbt context. The goal is to share this concept of a hybrid SQL-Python programming style in dbt Cloud to leverage the strengths and circumvent the weaknesses of both languages, and show that dbt Cloud can effectively function as a mini machine learning pipeline. The blog is targeted towards developers that are unfamiliar with the use of Python in dbt and intents to help them get started. Furthermore, I aim to convince developers to think about machine learning applications within the context of their dbt projects supported by a case study that I personally developed (Machine learning based time series forecasting to predict client demand). Lastly, I hope to convey the idea that machine learning in dbt is not as complex as people might think it is, and show that through Python's many machine learning libraries, A.I. implementation is more accessible than ever.  

### Link to an initial outline.

https://docs.google.com/document/d/1AGHFfF23gkvUXaB1Cv7AVFkvylHyiZtF_SZ93dxB0HM/edit?usp=sharing

**Comment by KiraFuruichi** [comment]
Hey @niels-tropos thank you for opening up this issue! My name is Kira and I'm a technical writer here at dbt Labs who helps shepherd the Developer Blog.

Your proposal and outline look amazing! The team is always eager for more folks to be working with Python models and after giving your outline a quick read, it looks like it's a great candidate for a blog post here :)

I’ve assigned myself and @dbeatty10 as the primary editors and support for this article; Doug and I can help you with editing passes, getting the posts live on our site, and promoted on our social. We aim for a ~6 week turnaround time for posts from Issue to Publication, but also work on your timing (especially with the holidays coming up) 🙂 Doug and I are also OOO all next week, so we likely won't be responding to any comments next week.

My biggest point of feedback at this point is that I think the bulk of your blog should be focused on sections 4 and 5 from your outline, since I feel like that's where the real punch of your article is at and is the most actionable for end-readers. Please give myself and Doug (kira.furuichi@dbtlabs.com and doug.beatty@dbtlabs.com) comment access, so we can do back and forth edits if needed :) 

Next steps is for you to expand your outline to a fully-formed draft in the following weeks. We'll work back and forth here on editing/ideation to get into its final form. If you need any support while you're writing, whether it's technical or editorial, please don't hesitate to reach out here.

Let me know if you have any questions, but we're excited to work with you and get this up!

**Comment by niels-tropos** [comment]
Hey @KiraFuruichi and @dbeatty10! Hope you had a great holiday season.

I gave you both commenting rights on the google docs page. I only very recently came back from holiday myself and haven't had a chance to expand the outline yet. I will be doing this in the next few days, likely in the weekend as I also have a lot of work to catch up to.

I will give a little ping when there is something to review :) 

Happy to be working on this!

**Comment by dbeatty10** [comment]
@niels-tropos Do you have an estimate of when you'll be able to expand the outline into a full first draft?

The ideal situation would be to have a first draft by 16 January if you are able.

**Comment by niels-tropos** [comment]
Hi @dbeatty10! In typical new years fashion, everybody is extremely ambitious and driven to get work done, so is the client I am currently working for. I'm very busy for the moment leaving little time to work on non-client related projects. However, I have planned to work on the draft at the end of this week. The first draft should be ready before the 16th of January.

**Comment by dbeatty10** [comment]
Isn't that the truth?! 😅 

Sounds good @niels-tropos -- looking forward to it!

**Comment by niels-tropos** [comment]
Hi there! Short update: I'm currently hard working on the draft. Most of the introductory text is finished. I am currently trying to save a trained forecasting model in an internal stage in Snowflake using a dbt post hook. I am still figuring this out but I think it is essential to share in the blog as we want to avoid retraining ml models everytime a python model runs. I want to make sure I cover all relevant aspects of ml ops, including saving and loading back in a pre-trained model. Link to current draft version here: https://docs.google.com/document/d/16hn76ZVxIAS3RaF7bLL2Yr3HqiN516gn83_U17eIwKU/edit?usp=sharing

**Comment by dbeatty10** [comment]
Awesome @niels-tropos !

In terms of saving a trained forecasting model, this is something @lostmygithubaccount (Cody) has done before. I'm guessing it's not the _only_ way it can be done, but Cody will follow-up later and share his solution with you!

**Comment by lostmygithubaccount** [comment]
hi @niels-tropos, so the way I went about solving this is to add a `train_new_model=True/False` variable and use that in the code to determine whether to A) train a new model or B) load in a previous one. You can see my example of that here: https://github.com/dbt-labs/coalesce-2022-python-databricks/blob/solutions/models/challenges/ml/cluster_py.py

as you can see in my `TODO`, I would recommend moving that variable to a config file and using it from there. then you know, in code, whether a model is being re-trained or not and can override with the CLI. I haven't tested that myself, but it should work using `dbt.config.get("train_new_model")`, overviewed in here: https://docs.getdbt.com/docs/build/python-models#accessing-project-context

quick edit/update: I think these MLOps flows in dbt are also subject to further discovery and input from the community! we're in the very early days of this and very excited to see you and others starting the journey with us

**Comment by runleonarun** [comment]
@dbeatty10 and @niels-tropos Do you have a status for this blog post? Just curious if we should close this issue.

**Comment by runleonarun** [comment]
Hey friends, I am going to close this issue, but feel free to open it if it picks up some steam!
