### ISSUE TITLE
incremental-models.md -- is_incremental filter: inconsistent use of > vs. >=

### ISSUE THREAD

**Issue by bbrewington** [fishtown-analytics/docs.getdbt.com#2606]
This uses ">":

https://github.com/dbt-labs/docs.getdbt.com/blob/b0e3915f0c705a4d57c3135d22f1557271b9cbe5/website/docs/docs/build/incremental-models.md?plain=1#L59

This uses ">=":

https://github.com/dbt-labs/docs.getdbt.com/blob/b0e3915f0c705a4d57c3135d22f1557271b9cbe5/website/docs/docs/build/incremental-models.md?plain=1#L131

**Comment by owenprough-sift** [comment]
This could be intentional. The former looks like it's using a timestamp, so you'd want to load new/updated rows that have occurred since the last table load. The latter looks like it's using day-level precision, so you would want `>=` to catch new/changed rows that occurred on-the-same-date-but-chronologically-after the latest incremental table run.

**Comment by bbrewington** [comment]
yep, I think you're right.  Maybe it would be good to explain in the commentary on the page, the use of > for timestamp and >= for date

**Comment by dbeatty10** [comment]
Thanks @bbrewington and @owenprough-sift !

@bbrewington are you willing to suggest an update to the commentary?

It's as easy as:
1. Going here: https://docs.getdbt.com/docs/build/incremental-models
2. Scroll to the bottom of the page
3. Click the "[Edit this page](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/docs/build/incremental-models.md)" link
4. Make your proposed edits
5. Click the "Propose changes" button at the bottom of the page
