### ISSUE TITLE
After May 10th: Change branch protection to the `current` branch

### ISSUE THREAD

**Issue by aranke** [fishtown-analytics/docs.getdbt.com#3181]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

N/A, issue is for this repo

### What changes are you suggesting?

Branch Protection docs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

Enabling this rule means you don't have to dismiss reviews as stale.
You can also iterate on a PR async post-approval without needing a new one.

### Additional information

Happy to help set this up; it's a best practice, so I thought I'd mention it here.

**Comment by runleonarun** [comment]
Hey @aranke! This is the branch protection rule we set up because we wanted to avoid unreviewed content being merged and we didn't want to force a CODEOWNERS or Docs team review for every PR. 

cc: @jtcohen6 I'd love to hear your thoughts as well!  How do you solve this on Core? Can everyone at dbt provide an approving reviewing on Core content? 

![Screenshot 2023-04-14 at 4 18 03 PM](https://user-images.githubusercontent.com/3880403/232169644-adc3246b-9d10-4a60-bd17-c504bfe866b2.png)

**Comment by jtcohen6** [comment]
@runleonarun In the `dbt-core` repo, we require approvals in order to merge PRs, and someone with ~"write" access~ the "Maintain" role has to actually press "merge." (Or, an "admin" can optionally merge without approval & even if CI checks haven't passed.)

The approval doesn't need to be from a CODEOWNER, but it does need to be from someone who has "write" access on the repository. (I like that approvals from GitHub users with "write" access appear as green checks, whereas approvals from GitHub users without "write" access appear as grey checks.)

We don't have this setting enabled:
> Dismiss stale pull request approvals when new commits are pushed

It's fairly common for a PR reviewer to leave a review with non-blocking suggestions/comments. It should be up to the PR author's discretion to incorporate those small suggestions (or not), and still retain the approval that enables them to merge, without requiring the PR reviewer from taking another pass over the same code they already approved. This does mean that PR authors _could_ substantially rework their changes _after_ getting approval for different-looking code; that's on them, and the honor system. Ultimately, it does need to be someone with ~"write" access~ the "Maintain" role (a member of the team) who merges PRs.

<img width="778" alt="Screenshot 2023-04-18 at 18 58 41" src="https://user-images.githubusercontent.com/13897643/232850603-2bd41967-9e5a-46e6-9a07-f5455b34814b.png">

**Comment by runleonarun** [comment]
Thanks Jeremy!!
I would like to make this change to match how dbt-core works. I will reach out to our main stakeholders to let them know about this.

**Comment by runleonarun** [comment]
Thanks @jtcohen6 and @aranke, here are my action items to follow up on these changes. 

Follow-up items for Leona:
- [x] Communicate change to stakeholders
- [x] Chat with Ganz & DX
- [x] Post communication in #community-product-docs channel so Front-end team is aware and Partnerships

By mid May, make these changes:
   - [x] remove the making commits dismisses reviews by deselecting this: 
![Screenshot 2023-04-18 at 5 30 40 PM](https://user-images.githubusercontent.com/3880403/233202492-09cd3bc5-c9a0-4dc7-a166-a451b68f14de.png)
   - [x] Restrict who can merge pull requests by restricting who can push to matching branches:
![Screenshot 2023-04-18 at 5 28 54 PM](https://user-images.githubusercontent.com/3880403/233203161-a3ad2ec8-2b09-40c9-9eba-60af537840ef.png)
- [ ] Figure out if we want to add teams who can dismiss reviews (otherwise it’s just admins, which might be OK)
![Screenshot 2023-04-18 at 5 30 24 PM](https://user-images.githubusercontent.com/3880403/233203414-e536d7ed-70c0-474b-9e2b-b0a44d3f236f.png)

**Comment by runleonarun** [comment]
Just a status update that I will make this change after May 10th.

**Comment by runleonarun** [comment]
This is complete!
