### ISSUE TITLE
Document that dbt Cloud-supported versions get security patches

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3521]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/core

### What part(s) of the page would you like to see updated?

Per [this internal conversation](https://dbt-labs.slack.com/archives/C0131TY7EEA/p1686668217878079), let's make sure to mention that Cloud supported versions will get security patches. 

Some questions for @jtcohen6:
* Should we refine [these definitions](https://docs.getdbt.com/docs/dbt-versions/core#ongoing-patches) to represent the event that any version is also a Cloud supported version?
* Should we add an asterisk to the Cloud-supported versions and a note mentioning they are also getting security fixes?
* Should we add an EOL definition?

For the writer addressing this issue:
* Reminder: the Releases table also shows up on the [upgrading core in cloud](https://docs.getdbt.com/docs/dbt-versions/upgrade-core-in-cloud#latest-releases) page, so we should make sure to add any of this context over there too (or add it to the reusable).

**Comment by jtcohen6** [comment]
We don't have an update here beyond the language that we added in https://github.com/dbt-labs/docs.getdbt.com/pull/3333:

> All dbt Core versions v1.0 and later are available in dbt Cloud until further notice. In the future, we intend to align dbt Cloud availability with dbt Core ongoing support. You will receive plenty of advance notice before any changes take place.

We haven't been putting out new patches of v1.0 or v1.1 since their EOL dates. We have been backporting certain changes to the `1.0.latest` and `1.1.latest` branches of `dbt-core`, so that we can continue running automated tests, while those versions continue to be available in dbt Cloud.
