### ISSUE TITLE
Metric nodes `depends_on` will include semantic_models based on measures, but not based on filters

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3682]
Somewhere in these docs:
- https://docs.getdbt.com/docs/build/measures
- https://docs.getdbt.com/docs/build/semantic-models

Let's capture that metric nodes will reflect dependencies on semantic models for their _measures_, but will not reflect dependencies based on _filters_, for the purposes of:
- dbt selection syntax
- visualizing the DAG (in dbt-docs & IDE)

### Context

(from Quigley)

There are three-ish places that metrics need to source the nodes for it's `depends_on` attribute

1. `Metric.type_params.input_metrics` for `RATIO` and `DERIVED` type metrics
2. `Metric.type_params.measure` for `SIMPLE` and `CUMULATIVE` type metrics
3.  From filters
  a. `Metric.filter`
  b. `Metric.type_params.measure.filter`
  c. `Metric.type_params.input_metrics[x].filter`

The work for 1 and 2 exist currently on dbt-labs/dbt-core#8015.

Number 3 is a bit harder though. This is because
A. The spec for filters actually isn't finalized yet. The MetricFlow team is working on support for dunders
B. Which semantic model a dimension comes from in a filter is determined at query time (because a dimension can exist on multiple semantic models and the optimal join path is calculated).

Thus this issue is just to resolve 1 & 2, whereas 3 will be pushed off and become a separate core ticket/issue

_Originally posted by @QMalcolm in https://github.com/dbt-labs/dbt-core/issues/7854#issuecomment-1622594683_

**Comment by jtcohen6** [comment]
```
dbt list --select my_semantic_model+
```

will include metrics defined on that semantic model

**given that we only just merged the PR for this, let's confirm it actually works**

if (and only if) the metrics are defined to use one of that semantic model's _measures_ (or derived metrics downstream of those metrics)

but if a metric only references a semantic model by specifying one of its _dimensions_ in its _filters_ - it will not be considered downstream of that semantic model

**Comment by jtcohen6** [comment]
@mirnawong1 Just caught that you self-assigned this. I also asked @QMalcolm to help out here, so he can clarify / answer any questions / pitch in as well!

**Comment by mirnawong1** [comment]
## Dependencies

Metric nodes will reflect dependencies on semantic models for their _measures_. However, dependencies based on filters should not be reflected in:

- dbt selection syntax
- Visualization of the <Term="DAG"/> in dbt-docs and the [integrated development environment](/docs/cloud/dbt-cloud-ide/develop-in-the-cloud)(IDE).

This is because metrics need to source nodes for their `depends_on` attribute from three different places:

- `RATIO` and `DERIVED` type metrics should reference `Metric.type_params.input_metrics`.
- `SIMPLE`  type metrics should reference `Metric.type_params.measure`.
