### ISSUE TITLE
Add AWS Glue adapter to trusted list

### ISSUE THREAD

**Issue by mehdimld** [fishtown-analytics/docs.getdbt.com#4091]
### Link to adapter repo

https://github.com/aws-samples/dbt-glue

### Contact Details

mehdmldj@amazon.com

### Which of these best describes you?

I work for the vendor on top of which the dbt adapter functions

### Please agree to the each of the following

- [X] I am a maintainer of the adapter being submited for Trusted status
- [X] I have read both the [Trusted adapters](https://docs.getdbt.com/docs/trusted-adapters) and [Building a Trusted Adapter](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/8-building-a-trusted-adapter) pages.
- [X] I believe that the adapter currently meets the expectations given above
- [X] I will ensure this adapter stays in compliance with the guidelines
- [X] I understand that dbt Labs reserves the right to remove an adapter from the trusted adapter list at any time, should any of the below guidelines not be met

### What icon should be used?

<img width="272" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/38988556/73d76a3f-fd2f-45bc-962a-9f54a755a1fa">

**Comment by dataders** [comment]
discussed offline with @mehdimld and @menuetb -- we're going to hold off on adding to Trusted, until the [aws-samples/dbt-glue](https://github.com/aws-samples/dbt-glue) repo has CI run against the dbt-adapter-test suite that shows the adapter is in working order. I opened https://github.com/aws-samples/dbt-glue/issues/240 to document the work

for now I'm going to close this issue so that it doesn't interfere with the product docs team's triage process/states

**Comment by moomindani** [comment]
Thanks for your advise, we have added CI and resolved https://github.com/aws-samples/dbt-glue/issues/240.
Can we move forward?
