### ISSUE TITLE
Trouble searching for `use_colors`

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4365]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Algolia search & Google search results

### Desired search results

Here's the pages that I'd expect to show up in both a Google search as well as Algolia search:
- https://docs.getdbt.com/reference/global-configs/logs#color
- https://docs.getdbt.com/reference/global-configs/print-output#print-color

### What changes are you suggesting?

I was trying to search for the exact syntax to allow me to turn off colorization within my logs/dbt.log, but leave the colorization within the CLI.

I did a google search like this:
- https://www.google.com/search?q=dbt+profiles+color

Using the search bar in docs.getdbt.com didn't work either:

<img width="400" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/7d141e09-b0d1-4aa2-8b68-db8db8e63e78">

I'd expect this to have more search results too:

<img width="400" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/62b39327-b7ad-4c9f-8da7-f838ee89e94a">

**Comment by runleonarun** [comment]
So weirdly, my first google result is the print output page!

![Image](https://github.com/dbt-labs/docs.getdbt.com/assets/3880403/df7f7e7e-d236-4cdc-b0cc-ed7b8bebadab)

I am going to close this because we're going to address the Algolia search problems in a different manner (hopefully by getting an AI chatbot to help us)
