### ISSUE TITLE
Clarify dbt Mesh docs staging env job requirement

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#6068]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

@wusanny from the support team internally flagged a couple of questions/feedback wrt the dbt mesh cross-project ref doc staging environment section:

- Clarify what _..in a project without "fail-over" to Production_ means in [this section of the doc](https://docs.getdbt.com/docs/collaborate/govern/project-dependencies#staging-with-downstream-dependencies)
- Update the doc(s) so users know that they have to run a job in the staging environment of the upstream project in order for the downstream cross-projet ref to resolve. (Maybe as a prereq as user suggested)

### What part(s) of the page would you like to see updated?

- cross project ref doc: https://docs.getdbt.com/docs/collaborate/govern/project-dependencies#staging-with-downstream-dependencies

- possibly also: https://docs.getdbt.com/guides/mesh-qs?step=5

**Comment by mirnawong1** [comment]
@wusanny [raised this again](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1726808080917889?thread_ts=1726468745.734389&cid=C02NCQ9483C) as another user was having the same issue.

**Comment by nataliefiann** [comment]
Add sentence: "Execute a job in the staging environment of the upstream project in order for the downstream cross-project ref to resolve"

Also queried what fail-over to production means here: https://dbt-labs.slack.com/archives/C04MEJT5VPY/p1729159060525869 and https://dbt-labs.slack.com/archives/C017GDLAF7D/p1729159182261669

**Comment by nataliefiann** [comment]
Fail-over to production =

"This means: dbt Cloud will always use metadata from the Staging environment to resolve references in downstream projects — even if the configured Staging environment does not have any successful runs.
The docs say "fail-over" here because that's what a user might expect — that if there are no successful runs in Staging (= no metadata), dbt Cloud would look for metadata from successful runs in Production instead — but this is NOT what happens. One reason that customers define Staging environments is explicitly to prevent data from Production environments from "leaking" into lower environments, and so we wouldn't want to risk that happening."
