### ISSUE TITLE
Document --resource-type selector method

### ISSUE THREAD

**Issue by jaypeedevlin** [fishtown-analytics/docs.getdbt.com#622]
## Steps to reproduce:
Go to https://docs.getdbt.com/reference/node-selection/methods

## Expected results:
Expect to see documentation on `--resource-type`.  An example is included under the [exposure method](https://docs.getdbt.com/reference/node-selection/methods#the-exposure-method) but it isn't explicitly documented.

## Actual results
It wasn't there :)

**Comment by jtcohen6** [comment]
Today, only the `ls (list)` command can use the `--resource-type` flag, since it's the only task that can select resources of any type. So I think the most straightforward change here should be changing this line:

https://github.com/fishtown-analytics/docs.getdbt.com/blob/a36e4f0de36a54194584a7dde7eb14a0f5fb9a75/website/docs/reference/node-selection/syntax.md#L13

To:
```
 | ls (list) | `--select`, `--models`, `--exclude`, `--selector`, `--resource-type` | 
 ```


The `list` page already documents `--resource-type`. Though, while we're at it:
https://github.com/fishtown-analytics/docs.getdbt.com/blob/a36e4f0de36a54194584a7dde7eb14a0f5fb9a75/website/docs/reference/commands/list.md#L13

Should probably include `exposure`, too :)

**Comment by jaypeedevlin** [comment]
Thanks Jeremy, I'll put a PR in with these changes soon!
