### ISSUE TITLE
Make threads more visible in docs 

### ISSUE THREAD

**Issue by annafil** [fishtown-analytics/docs.getdbt.com#703]
Via [Community Slack](https://getdbt.slack.com/archives/C2JRRQDTL/p1624303779285100)

<img width="535" alt="Screen Shot 2021-06-21 at 12 53 47 PM" src="https://user-images.githubusercontent.com/7892219/122819781-ba23d980-d28f-11eb-82af-84f793305aaa.png">

Some docs on this exist, but they are only for CLI and not very easy to discover. Per @amychen1776 this question comes up a lot for folks getting started. Also imagine this is a pattern Airflow users are familiar with, and might be looking out for. 

**Proposal:** have this info live on its own page instead, and cover both CLI and Cloud

cc @sophiad96 @amychen1776 

h/t @jtcohen6 for link to [a good article on the subject that may be helpful too](https://blog.getdbt.com/how-we-made-dbt-runs-30--faster/).

**Comment by sophiad96** [comment]
@annafil do you have any thoughts on where in the docs we should add this? I'm going to think about this a bit more today but would love to hear your thoughts!

**Comment by amychen1776** [comment]
@annafil Picking this up since I have one Snowflake specific recommendation about threads: what are your thoughts at putting them in our best practices section as well as this jobs page on [dbt Cloud](https://docs.getdbt.com/docs/dbt-cloud/cloud-quickstart#create-a-new-job)

Using threads has always been our best practices and my inkling is that this page does get some amount of traffic: https://docs.getdbt.com/docs/guides/best-practices
