### ISSUE TITLE
--fail-fast is available for `test` and `build` but isn't documented.

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#911]
I opened https://github.com/dbt-labs/dbt-rpc/issues/65 because the docs implied that `--fail-fast` was only available on `dbt run`, not `dbt test` or `dbt build`. It turns out it is supported in both, _but not on dbt Cloud because the rpc server doesn't support it_. 

The docs for [build](https://docs.getdbt.com/reference/commands/build) and [test](https://docs.getdbt.com/reference/commands/test) should be updated to have equivalent documentation as https://docs.getdbt.com/reference/commands/run#failing-fast 

Or, should fail-fast be pulled out instead of repeating the same info over and over? Depends on our docs strategy cc @runleonarun

**Comment by jtcohen6** [comment]
> Or, should fail-fast be pulled out instead of repeating the same info over and over?

This is what I did for all "global configs" in prerelease docs for v1: https://github.com/dbt-labs/docs.getdbt.com/blob/next/website/docs/reference/global-configs.md#failing-fast

It's now a global CLI flag that precedes the subcommand. Because all I did was copy-paste-move, `dbt run` is still the only command explicitly mentioned there.

**Comment by runleonarun** [comment]
@joellabes do we just need to refer to the global command from build and test now?

**Comment by joellabes** [comment]
Yeah i think thatd do it!

**Comment by runleonarun** [comment]
Assigning to @genwhitt

**Comment by nghi-ly** [comment]
Fixed with PR #3347
