### ISSUE TITLE
Typo in Upgrading dbt versions in Cloud doc

### ISSUE THREAD

**Issue by nathan-protempo** [fishtown-analytics/docs.getdbt.com#964]
Under the "Upgrading to v1.0.latest from v0.21" summary in the [Upgrading dbt versions in Cloud](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-upgrading-dbt-versions) doc, the dbt_project.yml example looks like this:

```
model-paths: ["models"] # formerly named "model-paths"
seed-paths: ["data"]    # formerly named "data-paths"
clean-targets:
  - "target"
  - "dbt_packages"      # formerly named "dbt_modules"
```

I think the first line is meant to read:

`model-paths: ["models"] # formerly named "source-paths"`

**Comment by runleonarun** [comment]
Thanks for calling this out, @nathan-protempo. It looks [like you are correct](https://github.com/dbt-labs/docs.getdbt.com/pull/913/files#diff-30657b63cb4a3a50988af3428f472b546e9eb25f0f6acef83456d7ec65c065f1R18) and it was likely a copy-paste error. You are welcome to spin up a PR for this, otherwise we will get to this as soon as we can. 🙇🏻‍♀️

**Comment by nathan-protempo** [comment]
Thanks @runleonarun I have created a PR for this https://github.com/dbt-labs/docs.getdbt.com/pull/1014
