### ISSUE TITLE
Clarify that you can't override the `builtin` macros via a package

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#971]
See also: https://github.com/dbt-labs/dbt-core/issues/4491 

Both I and the user who opened ☝️  this issue lost a lot of time trying to make this work using deferral, following the instructions in the docs. It ultimately turns out that ref, source, config (and maybe others) aren't deferred so it's impossible. 

You can overwrite in your own project, but not via a package. It'd be worth calling out this exception in https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#overriding-global-macros and https://docs.getdbt.com/reference/dbt-jinja-functions/builtins#usage

**Comment by runleonarun** [comment]
Thanks for capturing this, Joel. I added it to our to-do list!

**Comment by mirnawong1** [comment]
hey @joellabes , happy to get this updated! before i do, this is still relevant/current, yes?

**Comment by joellabes** [comment]
Yep!

**Comment by pSpitzner** [comment]
I just spend way too long to figure out what does and does not work, so I hope the next person might stumble over this:

- The docs currently say that you can override `generate_schema_name` in your package. You can, indeed.
- But they are a bit misleading from the example, where the macro is overriden via `generate_schema_name` but not `default__generate_schema_name`.
- This confused me because the override works fine with `generate_schema_name` when placed inside the project, but when it is in the package, it _needs_ to be`default__generate_schema_name` prefix. I had assumed setting the dispatch order (to project, package, dbt) would suffice - it did not.
- The docs currently hint that you should overrite `default__` but do not make this explicit as a difference to the preceding example.
